version: '3.8'

services:
  avto-ria-clone-postgres:
    image: postgres:16.1
    ports:
      - '${POSTGRES_PORT}:5432'
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-password}'
      POSTGRES_DB: '${POSTGRES_DB:-avto-ria-clone-khynotska}'
    volumes:
      - ./avto-ria-clone-api-db:/var/lib/postgresql/data

  avto-ria-clone-redis:
    image: redis:7.2.3
    ports:
      - '${REDIS_PORT:-6379}:6379'
    command: >
      --requirepass '${REDIS_PASSWORD:-redispass}'
    restart: unless-stopped

  avto-ria-clone-s3:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    restart: unless-stopped
    ports:
      - "7002:9000"
      - "7001:9001"
    volumes:
      - ./avto-ria-clone-api-s3-data:/usr/src/app/s3
    environment:
      - MINIO_ROOT_USER=khynotskauser
      - MINIO_ROOT_PASSWORD=khynotskapassword

volumes:
  avto-ria-clone-api-db:
  avto-ria-clone-api-s3-data:
